# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Junyung Ji
title: Ph.D. student
email: jee9894@hanyang.ac.kr
# website: www.github.com/jiogenes

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: jiogenes
linkedin_username: jiogenes
orcid_username: 0000-0003-4587-4337
# twitter_username: facespics
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# Additional icon links
additional_links:
  - title: blog
    icon: fas fa-globe
    url: https://jiogenes.github.io/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Junyung Ji and I'm a Ph.D. student in Hanyang university at Ansan. I have a strong interest in natural language processing (NLP) within the field of artificial intelligence (AI). My research focuses on the applications of prompt engineering and Retrieval-Augmented Generation (RAG) techniques in large language models (LLM). My advisor is [Younghoon Kim](https://sites.google.com/site/nongaussian) and I am studing in the [Big Data Mining Lab.](https://nongaussian.github.io/)

  I am most skilled in: <mark>Python</mark> language and <mark>Pytorch</mark> , <mark>Huggingface</mark> library.

content:
  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: "Predicting Missing Values in Survey Data Using Prompt Engineering for Addressing Item Non-Response"
        # link: https://www.mdpi.com/2306-5354/10/11/1280
        # link_text: link
        sub_title: Junyung Ji, Jiwoo Kim and Younghoon Kim
        caption: Future Internet 2024 (Under Review)

      - layout: top
        title: "Pixel Diffuser: Practical Interactive Medical Image Segmentation without Ground Truth"
        # link: https://www.mdpi.com/2306-5354/10/11/1280
        # link_text: link
        sub_title: Mingeon Ju, Jaewoo Yang, Jaeyoung Lee, Moonhyun Lee, Junyung Ji and Younghoon Kim
        caption: Bioengineering 2023, 10(11), 1280
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
          # Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Hanyang University
        caption: 2022 - current
        sub_title: Master Doctorate Integrated Course in Artificial Intelligence

      - layout: top
        title: Ulsan University
        caption: 2014 - 2020
        sub_title: Bachelor of Science in Computer Science & Engineering

  - title: Teaching Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Data Mining
        caption: Second semester 2024
        sub_title: Teaching assistant

      - layout: top
        title: Machine Learning
        caption: First semester 2024
        sub_title: Teaching assistant

      - layout: top
        title: Program Design Methodology
        caption: Second semester 2023
        sub_title: Teaching assistant

      - layout: top
        title: Digital Logic Circuit Design
        caption: First semester 2023
        sub_title: Teaching assistant

      - layout: top
        title: Understanding of Artificial Intelligence
        caption: Second semester 2022
        sub_title: Teaching assistant

      - layout: top
        title: Logical Foundations of Programming
        caption: First semester 2022
        sub_title: Teaching assistant

  - title: Industrial Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mommydndn, Inc.
        link: https://mommydndn.com/
        sub_title: Mobile App Development Team Lead
        caption: October 2021 - March 2022
        description: | # this will include new lines to allow paragraphs
          I was responsible for the initial phase of app development, leading the planning and implementation of key features to establish the foundation for the project's success. My efforts ensured that the groundwork was effectively laid for future development stages.

      - layout: left
        title: Opel Solution, Inc.
        link: https://www.opelsolution.ai/
        sub_title: Mobile Application & Firmware Developer
        caption: September 2020 - October 2021
        description: | # this will include new lines to allow paragraphs
          I developed an mobile app between an OBD dongle and users for vehicle data transmission and reception, along with an Android and Flutter. Additionally, I contributed to the development of the OBD dongle firmware.

      - layout: left
        title: Navis Automotive Systems, Inc.
        link: https://www.navis-ams.com/
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: July 2019 - January 2020
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          I developed and maintained a driving guidance system for vehicle navigation, focusing on improving the accuracy and quality of driving assistance.

  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title: sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: Researching today for a smarter tomorrow.

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
